import { useState } from 'react';
import { submitManualVerification } from '../api.js';

export default function ManualVerification({ onClose }) {
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const [documents, setDocuments] = useState([]);
  const addDocuments = (event) => { const added = Array.from(event.target.files); event.target.value = ''; if (documents.length + added.length > 5) { setError('A maximum of 5 verification documents can be uploaded. Remove a document before adding another.'); return; } setDocuments((current) => [...current, ...added]); setError(''); };
  const removeDocument = (index) => { setDocuments((current) => current.filter((_, itemIndex) => itemIndex !== index)); setError(''); };
  const submit = async (event) => { event.preventDefault(); if (!documents.length) { setError('Please add at least one verification document.'); return; } setSending(true); setError(''); const form = new FormData(event.currentTarget); documents.forEach((document) => form.append('documents', document)); try { await submitManualVerification(form); setMessage('Submitted'); event.currentTarget.reset(); setDocuments([]); } catch (err) { setError(err.message); } finally { setSending(false); } };
  if (message) return <div className="modal" role="presentation"><div className="modal-box thank-you" role="dialog" aria-modal="true"><div className="success-icon">✓</div><h2>Thank you for registering</h2><p>Your hospital details and documents have been submitted for review.</p><p>Once approved, you will receive an account-setup link at the Gmail address you provided.</p><div className="modal-actions"><button className="primary" onClick={onClose} type="button">Back to home</button></div></div></div>;
  return <div className="modal" onClick={onClose} role="presentation"><div className="modal-box" onClick={(event) => event.stopPropagation()} role="dialog" aria-modal="true"><h2>Manual hospital verification</h2><p>For hospitals without a website. Upload official documents for an administrator to review.</p><form onSubmit={submit}><label>Hospital name<input name="hospitalName" placeholder="e.g. City Care Hospital" required /></label><label>Hospital address<textarea name="address" placeholder="Street, city, state and PIN code" required /></label><label>Hospital contact number<input name="contactNumber" type="tel" placeholder="e.g. +91 98765 43210" required /></label><label>Gmail address (used as your username)<input name="workEmail" type="email" placeholder="hospital.admin@gmail.com" required /></label><div className="document-upload"><input className="file-picker" id="verification-documents" type="file" accept=".pdf,.png,.jpg,.jpeg" multiple onChange={addDocuments} /><label className="upload-button" htmlFor="verification-documents">{documents.length ? 'Upload more documents' : 'Upload documents'}</label></div>{documents.length > 0 && <ul className="document-list">{documents.map((document, index) => <li key={`${document.name}-${index}`}><span>{document.name}</span><button className="remove-document" onClick={() => removeDocument(index)} type="button">Remove</button></li>)}</ul>}{error && <p className="login-error" role="alert">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={onClose} type="button">Close</button><button className="primary" disabled={sending} type="submit">{sending ? 'Submitting…' : 'Submit for review'}</button></div></form></div></div>;
}
